[files]
extend-exclude = [
    "*.json",
    "*.xml",
    "*.csproj",
    "*.sln",
    "*.yml",
    "*.yaml",
    "*.cs",
    "*.xaml",
    "*.vdproj",
    "*.binds",
    "typos.toml",
    "bin/**",
    "obj/**",
    "packages/**",
    ".vs/**",
    ".git/**"
]

[default.extend-words]
EdBindings = "EdBindings"
HOTAS = "HOTAS"
keybinding = "keybinding"
keybindings = "keybindings"
gameplay = "gameplay"
VoiceAttack = "VoiceAttack"
codebase = "codebase"
frameworking = "frameworking"
analyzers = "analyzers"
MinVer = "MinVer"
nullable = "nullable"
WiX = "WiX"
WixToolset = "WixToolset"
wixext = "wixext"
NSIS = "NSIS"
Chocolatey = "Chocolatey"
vdproj = "vdproj"
MSBuild = "MSBuild"
searchable = "searchable"
codecov = "codecov"
dropdown = "dropdown"
gamepad = "gamepad"
JSON = "JSON"
json = "json"
Golubev = "Golubev"
flaticon = "flaticon"
