---
name: 🐛 Bug Report
about: Report a bug or unexpected behavior
title: '[BUG] '
labels: ['bug', 'needs-triage']
assignees: ''
---

## 🐛 Bug Description
**Describe the bug**
A clear and concise description of what the bug is.

## 🔄 Steps to Reproduce
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See error

## ✅ Expected Behavior
A clear and concise description of what you expected to happen.

## ❌ Actual Behavior
A clear and concise description of what actually happened.

## 📸 Screenshots
If applicable, add screenshots to help explain your problem.

## 🖥️ Environment Information
**Application Version:**
- EdBindings Version: [e.g. v1.2.3]
- Installation Method: [MSI Installer / ZIP Archive / Built from source]

**System Information:**
- OS: [e.g. Windows 11 22H2]
- .NET Runtime: [e.g. .NET 8.0]
- Elite Dangerous Version: [e.g. Odyssey / Horizons]

**Hardware:**
- Input Devices: [e.g. Thrustmaster T.16000M, Logitech X56, etc.]
- Multiple Monitors: [Yes/No]

## 📄 Binding File Information
**Elite Dangerous Binding File:**
- Binding File Name: [e.g. Custom.4.0.binds]
- Custom Bindings: [Yes/No]
- Device Mapping Used: [e.g. X56, T.16000M, None]

## 📋 Additional Context
**Error Messages:**
```
Paste any error messages here
```

**Log Files:**
If available, please attach relevant log files or error details.

**Additional Information:**
Add any other context about the problem here.

## 🔧 Attempted Solutions
- [ ] Restarted the application
- [ ] Tried different binding file
- [ ] Checked device mapping settings
- [ ] Reinstalled the application
- [ ] Other: [Describe what you tried]

## 📝 Additional Notes
Any additional information that might be helpful in resolving this issue.
