name: ❓ General Question
description: Ask a question about EdBindings usage or configuration
title: '[QUESTION] '
labels: ['question', 'needs-triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Have a question about EdBindings? We're here to help!

  - type: textarea
    id: question
    attributes:
      label: ❓ Your Question
      description: What would you like to know?
      placeholder: Please ask your question here...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: 📂 Question Category
      description: What type of question is this?
      options:
        - Usage/How-to
        - Configuration
        - Device Setup
        - Elite Dangerous Integration
        - Technical Issue
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 🎯 Context
      description: What are you trying to achieve? Provide some background.
      placeholder: I'm trying to...

  - type: textarea
    id: attempted-solutions
    attributes:
      label: 🔍 What You've Tried
      description: Have you tried anything to solve this yourself?
      placeholder: I've already tried...

  - type: input
    id: app-version
    attributes:
      label: 📱 EdBindings Version
      description: Which version are you using?
      placeholder: e.g., v1.0.0