---
name: 💬 Feedback & Suggestions
about: Share your experience and suggestions for improvement
title: '[FEEDBACK] '
labels: ['feedback', 'needs-triage']
assignees: ''
---

## 💬 Feedback Type
**What kind of feedback is this?**
- [ ] General user experience
- [ ] UI/UX suggestions
- [ ] Performance feedback
- [ ] Documentation feedback
- [ ] Installation/Setup experience
- [ ] Feature appreciation
- [ ] Other: [Describe]

## 🎯 Overall Experience
**How would you rate your overall experience with EdBindings?**
- [ ] Excellent - Exceeds expectations
- [ ] Good - Meets expectations
- [ ] Average - Adequate but could be better
- [ ] Poor - Below expectations
- [ ] Very Poor - Significant issues

## ✅ What's Working Well
**What do you like about EdBindings?**
Tell us about the features, design, or functionality that you find valuable.

**Specific Highlights:**
- User interface design
- Performance
- Feature completeness
- Documentation quality
- Installation process
- Device support
- Elite Dangerous integration

## 🔧 Areas for Improvement
**What could be better?**
Share your thoughts on what could be improved or enhanced.

**Specific Areas:**
- [ ] User interface could be more intuitive
- [ ] Performance could be faster
- [ ] More device support needed
- [ ] Better error messages
- [ ] More customization options
- [ ] Improved documentation
- [ ] Other: [Describe]

## 🎮 Usage Context
**How do you use EdBindings?**
- Primary use case: [e.g. Streaming, Personal reference, VoiceAttack integration]
- Frequency of use: [Daily/Weekly/Monthly/Occasionally]
- Elite Dangerous play style: [e.g. Combat, Exploration, Trading, Mining]
- Input setup: [e.g. HOTAS + Pedals, Dual stick, Gamepad, KB+M]

## 💡 Suggestions
**Specific Improvement Ideas:**
If you have concrete suggestions for improvements, describe them here.

**Inspiration from Other Tools:**
Are there other applications or tools that handle similar functionality well?

## 📊 Workflow Integration
**How does EdBindings fit into your Elite Dangerous workflow?**
Describe how you currently use the application and how it could better integrate with your gaming setup.

**Integration with Other Tools:**
- VoiceAttack
- Streaming software
- Elite Dangerous tools
- Voice control software
- Other binding managers

## 🔮 Future Features
**What features would make EdBindings even better?**
Share your wishlist for future functionality.

## 👥 Community
**How did you discover EdBindings?**
- [ ] Elite Dangerous community
- [ ] Reddit
- [ ] YouTube/Twitch
- [ ] GitHub search
- [ ] Friend recommendation
- [ ] Other: [Describe]

**Would you recommend EdBindings to other Elite Dangerous players?**
- [ ] Yes, definitely
- [ ] Yes, with some reservations
- [ ] Maybe
- [ ] Probably not
- [ ] No

## 📝 Additional Thoughts
**Any other feedback or comments?**
Share any additional thoughts, experiences, or suggestions you have.