---
name: ðŸŒ Performance Issue
about: Report performance problems, slowdowns, or memory issues
title: '[PERFORMANCE] '
labels: ['performance', 'needs-investigation', 'needs-triage']
assignees: ''
---

## âš¡ Performance Issue Summary
**Describe the performance problem:**
A clear description of what performance issue you're experiencing.

**Performance Type:**
- [ ] Application startup is slow
- [ ] UI is laggy/unresponsive
- [ ] High CPU usage
- [ ] High memory usage
- [ ] Slow binding file parsing
- [ ] Application freezing
- [ ] Other: [Describe]

## ðŸ“Š Performance Impact
**How severe is the impact?**
- [ ] Critical - Application unusable
- [ ] High - Significantly impacts usability
- [ ] Medium - Noticeable but workable
- [ ] Low - Minor inconvenience

**Frequency:**
- [ ] Always occurs
- [ ] Often occurs (>50% of the time)
- [ ] Sometimes occurs (10-50% of the time)
- [ ] Rarely occurs (<10% of the time)

## ðŸ” Reproduction Steps
**Steps to reproduce the performance issue:**
1. 
2. 
3. 

**Specific Actions that Trigger the Issue:**
- [ ] Loading binding files
- [ ] Switching between devices
- [ ] Filtering/searching bindings
- [ ] Resizing window
- [ ] Scrolling through long lists
- [ ] Multiple device mappings
- [ ] Large binding files
- [ ] Other: [Describe]

## ðŸ“ˆ Performance Metrics
**If you can measure it, please share:**

**Timing Information:**
- Application startup time: [X seconds]
- File loading time: [X seconds]
- UI response time: [X milliseconds]

**Resource Usage:**
- CPU usage during issue: [X%]
- Memory usage: [X MB/GB]
- Disk usage: [High/Medium/Low]

**File Size Information:**
- Binding file size: [X KB/MB]
- Number of bindings: [Approximate count]
- Number of devices: [X]

## ðŸ’» System Environment
**Operating System:**
- [ ] Windows 11
- [ ] Windows 10
- [ ] Other: [Specify version]

**System Specifications:**
- CPU: [e.g. Intel i7-8700K, AMD Ryzen 5 3600]
- RAM: [e.g. 16GB DDR4]
- Storage: [e.g. SSD, HDD, NVMe]
- GPU: [If relevant]

**System Performance State:**
- [ ] High performance power mode
- [ ] Balanced power mode
- [ ] Power saver mode
- [ ] Other applications running: [List if relevant]

## ðŸ“± Application Context
**EdBindings Version:** [e.g. 1.2.0]

**Application State:**
- Window size: [e.g. Maximized, 1920x1080, Small window]
- Number of open binding files: [X]
- Device mappings loaded: [X]

**Concurrent Usage:**
- [ ] Elite Dangerous running
- [ ] VoiceAttack running
- [ ] Streaming software active
- [ ] Other binding tools open
- [ ] Multiple EdBindings instances

## ðŸŽ® Elite Dangerous Context
**Game State During Issue:**
- [ ] Game not running
- [ ] Game in menu
- [ ] Game in normal flight
- [ ] Game in combat
- [ ] Game loading
- [ ] VR mode active

**Binding Complexity:**
- Control scheme: [e.g. Complex HOTAS setup, Simple gamepad]
- Custom bindings: [Many/Some/Few/None]
- Multiple device types: [Yes/No]

## ðŸ”„ Comparison Information
**Performance Comparison:**
- Previous EdBindings versions: [Better/Same/Worse]
- Other similar applications: [How does performance compare]
- Fresh vs. long-running session: [Any difference]

## ðŸ› ï¸ Troubleshooting Attempted
**What have you tried?**
- [ ] Restarted the application
- [ ] Restarted the computer
- [ ] Closed other applications
- [ ] Tried with smaller binding files
- [ ] Checked Task Manager for resource usage
- [ ] Updated to latest version
- [ ] Ran as administrator
- [ ] Other: [Describe]

## ðŸ“‹ Additional Context
**Logs or Screenshots:**
If you can capture performance data (Task Manager screenshots, timing logs), please attach them.

**Pattern Recognition:**
Have you noticed any patterns in when the performance issues occur?

**Workarounds:**
Are there any workarounds you've found that help with the performance issue?