name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security scan every Sunday at 2:00 AM UTC
    - cron: '0 2 * * 0'

jobs:
  security-scan:
    runs-on: windows-latest

    permissions:
      security-events: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Run security audit
      run: |
        echo "# Security Audit Report" > security-report.md
        echo "Generated on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') UTC" >> security-report.md
        echo "" >> security-report.md

        try {
          # Check for known vulnerabilities in NuGet packages
          $auditOutput = dotnet list package --vulnerable --include-transitive 2>&1

          if ($auditOutput -match "no vulnerable packages") {
            echo "✅ No vulnerable packages found!" >> security-report.md
          } else {
            echo "## Vulnerable Packages Found:" >> security-report.md
            echo '```' >> security-report.md
            echo $auditOutput >> security-report.md
            echo '```' >> security-report.md
          }

          # Additional security checks
          echo "" >> security-report.md
          echo "## Additional Security Information:" >> security-report.md
          echo "- .NET Version: $(dotnet --version)" >> security-report.md
          echo "- Target Framework: net8.0-windows" >> security-report.md

        } catch {
          echo "❌ Error during security audit: $_" >> security-report.md
          exit 1
        }

    - name: Upload security report
      uses: actions/upload-artifact@v4
      with:
        name: security-audit-report
        path: security-report.md
        retention-days: 90

    - name: Initialize CodeQL
      if: github.event_name != 'schedule'
      uses: github/codeql-action/init@v3
      with:
        languages: csharp
        config: |
          paths:
            - src
          paths-ignore:
            - src/**/bin
            - src/**/obj

    - name: Autobuild
      if: github.event_name != 'schedule'
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      if: github.event_name != 'schedule'
      uses: github/codeql-action/analyze@v3
